version: 0.0
os: linux
# destination에 unzip된 파일을 저장할 디렉토리명을 넣음
files:
  - source: /
    destination: /home/ubuntu/e-eum/backend
permissions:
  - object: /home/ubuntu/e-eum/backend
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  AfterInstall:
    - location: scripts/start.sh
      timeout: 60
      runas: root